spring:
  application.name: api-gateway

server:
  port: 9090

logging.level:
  org.springframework.cloud: INFO

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://netflix:eureka@localhost:8761/eureka}

# Security
spring.security.user:
  name: admin
  password: s3cret