server:
  port: 8888

spring:
  application.name: config-server
  cloud.config.server:
    git:
      uri: https://github.com/ankurpapneja4/bookkeeper-project-config
      cloneOnStart: true
      search-paths: {application}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true